### ISSUE TITLE
Verbesserungen in Besprechungsprotokoll_2

### ISSUE THREAD

**Issue by Jotec1705** [Jotec1705/SE-Project2018#4]
@DE92 Nachdem ich mein Protokoll nochmal ein bisschen aufgehübscht habe hab ich mir deines auch mal kurz angeschaut. Folgende Kleinigkeiten sind mir aufgefallen (Treten von oben nach unten im Dokument auf):
-Tippfehler: DIE statt IDE
-Tippfehler: Intellij statt IntelliJ
-Formatfehler: Spaltengrenze "Schlussfolgerungen" sollte ein bis zwei Pixel nach rechts geschoben werden, damit das Wort in eine Zeile passt
-Tippfehler: Gui statt GUI
-Tippfehler: erstelen statt erstellen
-Tippfehler: Bosn statt Bosin

**Comment by DE92** [comment]
Angepasst
